# Generated by Django 3.2.16 on 2023-03-23 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_division_name', models.CharField(blank=True, max_length=250, null=True)),
                ('presidential_appointee', models.IntegerField(blank=True, null=True)),
                ('permanent', models.IntegerField(blank=True, null=True)),
                ('coterminus', models.IntegerField(blank=True, null=True)),
                ('jo_cos', models.IntegerField(blank=True, null=True)),
                ('casual_temporary', models.IntegerField(blank=True, null=True)),
                ('desktop_acer_installed', models.IntegerField(blank=True, null=True)),
                ('desktop_hp_installed', models.IntegerField(blank=True, null=True)),
                ('desktop_lenovo_installed', models.IntegerField(blank=True, null=True)),
                ('desktop_samsung_installed', models.IntegerField(blank=True, null=True)),
                ('mouse_installed', models.IntegerField(blank=True, null=True)),
                ('keyboardesktop_hp_installed', models.IntegerField(blank=True, null=True)),
                ('privacy_section', models.IntegerField(blank=True, default=0, null=True)),
                ('demographics_section', models.IntegerField(blank=True, default=0, null=True)),
                ('hardware_section', models.IntegerField(blank=True, default=0, null=True)),
                ('software_section', models.IntegerField(blank=True, default=0, null=True)),
                ('storage_section', models.IntegerField(blank=True, default=0, null=True)),
                ('competencies_section', models.IntegerField(blank=True, default=0, null=True)),
                ('trainings_section', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
