# Generated by Django 3.2.16 on 2023-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='office_division',
            fields=[
                ('office_division_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_division_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
