# Generated by Django 3.2.16 on 2023-03-24 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_office_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='office_division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_division_names', to='survey.office_division'),
        ),
    ]
