# Generated by Django 3.2.16 on 2023-03-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_office_division_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='laptop_acer_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_hp_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_lenovo_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_samsung_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
