# Generated by Django 3.2.16 on 2023-04-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20230412_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='age_18_24',
            new_name='age_20_24',
        ),
    ]
