# Generated by Django 3.2.16 on 2023-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_rename_age_18_24_survey_age_20_24'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='keyboardesktop_hp_installed',
            new_name='desktop_personal',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='mouse_installed',
            new_name='keyboard_office',
        ),
        migrations.AddField(
            model_name='survey',
            name='keyboard_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='monitor_office',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='monitor_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='mouse_office',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='mouse_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='scanner_office',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='scanner_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_office',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
