# Generated by Django 3.2.16 on 2023-04-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20230413_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='camera_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='coloredprinter_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='microphone_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='ordinaryprinter_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='photocopier_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='projector_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='scanner_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='speaker_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tv_shared_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
