# Generated by Django 3.2.16 on 2023-04-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20230413_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='camera_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='coloredprinter_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='desktop_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='keyboard_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='microphone_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='monitor_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='mouse_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='ordinaryprinter_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='photocopier_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='projector_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='scanner_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='speaker_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tv_need',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
