# Generated by Django 3.2.16 on 2023-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20230413_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='hardware_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
