# Generated by Django 3.2.16 on 2023-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_survey_hardware_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='desktop_others_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
