# Generated by Django 3.2.16 on 2023-04-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_survey_desktop_others_installed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='desktop_personal',
            new_name='desktop_acer_personal',
        ),
        migrations.AddField(
            model_name='survey',
            name='desktop_hp_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='desktop_lenovo_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='desktop_others_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='desktop_samsung_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
