# Generated by Django 3.2.16 on 2023-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20230419_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='laptop_personal',
            new_name='laptop_acer_personal',
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_hp_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_lenovo_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_others_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_others_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='laptop_samsung_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
