# Generated by Django 3.2.16 on 2023-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20230419_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tablet_acer_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_hp_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_lenovo_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_others_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_samsung_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
