# Generated by Django 3.2.16 on 2023-04-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20230419_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='tablet_office',
            new_name='tablet_acer_personal',
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_hp_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_lenovo_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_others_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tablet_samsung_personal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
