# Generated by Django 3.2.16 on 2023-04-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_competencyscale_icttrainingprograms_professionaltoolsoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='calendar_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_familiar', to='survey.competencyscale'),
        ),
        migrations.AddField(
            model_name='survey',
            name='creating_and_naming_folders_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_and_naming_folders_familiar', to='survey.competencyscale'),
        ),
        migrations.AddField(
            model_name='survey',
            name='dotr_issued_professional_tools_installed',
            field=models.ManyToManyField(blank=True, related_name='dotr_issued_professional_tools_installed', to='survey.ProfessionalToolsOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='gmail_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gmail_familiar', to='survey.competencyscale'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ict_trainings_interests',
            field=models.ManyToManyField(blank=True, related_name='ict_trainings_interests', to='survey.ICTTrainingPrograms'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ict_trainings_taken',
            field=models.ManyToManyField(blank=True, related_name='ict_trainings_taken', to='survey.ICTTrainingPrograms'),
        ),
        migrations.AddField(
            model_name='survey',
            name='meet_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meet_familiar', to='survey.competencyscale'),
        ),
        migrations.AddField(
            model_name='survey',
            name='personal_owned_professional_tools_installed',
            field=models.ManyToManyField(blank=True, related_name='personal_owned_professional_tools_installed', to='survey.ProfessionalToolsOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='professional_tools_needed',
            field=models.ManyToManyField(blank=True, related_name='professional_tools_needed', to='survey.ProfessionalToolsOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='saving_files_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_files_familiar', to='survey.competencyscale'),
        ),
    ]
