# Generated by Django 3.2.16 on 2023-04-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_communicationtoolsoption_productivityoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='communication_tools_installed',
            field=models.ManyToManyField(blank=True, related_name='communication_tools_installed', to='survey.CommunicationToolsOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='communication_tools_needed',
            field=models.ManyToManyField(blank=True, related_name='communication_tools_needed', to='survey.CommunicationToolsOption'),
        ),
    ]
