# Generated by Django 3.2.16 on 2023-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20230426_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='communication_tools_installed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='communication_tools_needed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
