# Generated by Django 3.2.16 on 2023-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20230426_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='dotr_issued_professional_tools_installed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='personal_owned_professional_tools_installed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='professional_tools_needed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
