# Generated by Django 3.2.16 on 2023-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20230426_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='dotr_issued_productivity_installed',
            field=models.ManyToManyField(blank=True, related_name='dotr_issued_productivity_installed', to='survey.ProductivityOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='dotr_issued_productivity_installed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='personal_owned_productivity_installed',
            field=models.ManyToManyField(blank=True, related_name='personal_owned_productivity_installed', to='survey.ProductivityOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='personal_owned_productivity_installed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='productivity_needed',
            field=models.ManyToManyField(blank=True, related_name='productivity_needed', to='survey.ProductivityOption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='productivity_needed_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
