# Generated by Django 3.2.16 on 2023-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20230426_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='software_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
